version: '3'
services:
  chatbox:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /home/qlud/TTS_Hieu/instantclient_11_2:/opt/oracle/instantclient
    environment:
      - LD_LIBRARY_PATH=/opt/oracle/instantclient
    restart: unless-stopped
